services:
  frontend:
    build:
      context: ./Ecommerce-Frontend
    ports:
      - "3000:3000"
    container_name: ecommerce_frontend
    volumes:
      - ./Ecommerce-Frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./Ecommerce-Backend
    ports:
      - "5000:5000"
    container_name: ecommerce_backend
    env_file:
      - ./Ecommerce-Backend/.env
    volumes:
      - ./Ecommerce-Backend:/app
      - /app/node_modules
